/*

 Top-level build file where you can add configuration options common to all sub-projects/modules.

 Add common repos here

*/

buildscript {
    // nothing for the project
}

apply from: file("${projectDir}/versions.gradle")

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
    buildscript {
        repositories {
            mavenLocal()
            mavenCentral()
            google()
        }
        dependencies {
            classpath "com.android.tools.build:gradle:$ANDROID_PLUGIN_VERSION"
        }
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace 'com.clover.remote.client.lib'
                }
            }
        }
    }
    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
}

